### ISSUE TITLE
MOD100 Support Discussion

### ISSUE THREAD

**Issue by iMatux** [bwp91/homebridge-meross#267]
Hello, first of all thank you for your work! This is a new Meross device which an RGB led and a diffuser which has 3 state (Off, Light Spray, Heavy Spray). I tried to set it manually with every field and model: "mod100", Home app recognise it as a light with intensity and a switch, so maybe there is an initial support in this plugin last version. If you need anything let me know.
This log below is from the other repo plugin, hope it helps. I hid fields like ip and macAddress.
`[MerossCloud] All-Data: {"all":{"system":{"hardware":{"type":"mod100","subType":"un","version":"3.0.0","chipType":"mt7682","uuid”:”******”,”macAddress”:”********”},”firmware":{"version":"3.1.5","compileTime":"2020/09/01 17:03:31 GMT +08:00","wifiMac”:”*******”,”innerIp”:”******”*,”server":"mqtt-eu.meross.com","port":443,"userId”:****},”time":{"timestamp":1618570318,"timezone":"Europe/Rome","timeRule":[[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1],[1919293200,3600,0]]},"online":{"status":1}},"digest":{"triggerx":[],"timerx":[],"diffuser":{"type":"mod100","light":[{"channel":0,"onoff":1,"lmTime":1618568005,"mode":0,"luminance":100,"rgb":255}],"spray":[{"channel":0,"mode":2,"lmTime":1618570307}]}}}}
[MerossCloud] System-Abilities: {"payloadVersion":1,"ability":{"Appliance.Config.Key":{},"Appliance.Config.WifiList":{},"Appliance.Config.Wifi":{},"Appliance.Config.Trace":{},"Appliance.System.All":{},"Appliance.System.Hardware":{},"Appliance.System.Firmware":{},"Appliance.System.Debug":{},"Appliance.System.Online":{},"Appliance.System.Time":{},"Appliance.System.Clock":{},"Appliance.System.Ability":{},"Appliance.System.Runtime":{},"Appliance.System.Report":{},"Appliance.System.Position":{},"Appliance.Control.Multiple":{"maxCmdNum":5},"Appliance.Control.TimerX":{"sunOffsetSupport":1},"Appliance.Control.TriggerX":{},"Appliance.Control.Bind":{},"Appliance.Control.Unbind":{},"Appliance.Control.Upgrade":{},"Appliance.Digest.TriggerX":{},"Appliance.Digest.TimerX":{},"Appliance.Control.Diffuser.Spray":{},"Appliance.Control.Diffuser.Light":{},"Appliance.Control.Diffuser.Sensor":{}}}`

**Comment by maslcar** [comment]
How did you configure it to show in HomeKit?

**Comment by iMatux** [comment]
> How did you configure it to show in HomeKit?

Like a supported Meross product, but in config.json model field is set to "MOD-100" ("MOD100" has the same behaviour), maybe is some sort of basic configuration when plugin doesn't recognise the device model. 
<img width="364" alt="Schermata 2021-04-17 alle 13 05 10" src="https://user-images.githubusercontent.com/23347512/115110935-0f84f700-9f7e-11eb-88c1-c80d8fc9603d.png">
![IMG_4967](https://user-images.githubusercontent.com/23347512/115110947-26c3e480-9f7e-11eb-8751-88ac7d87e7e1.PNG)

**Comment by maslcar** [comment]
> > How did you configure it to show in HomeKit?
> 
> Like a supported Meross product, but in config.json model field is set to "MOD-100" ("MOD100" has the same behaviour), maybe is some sort of basic configuration when plugin doesn't recognise the device model.
> <img alt="Schermata 2021-04-17 alle 13 05 10" width="364" src="https://user-images.githubusercontent.com/23347512/115110935-0f84f700-9f7e-11eb-88c1-c80d8fc9603d.png">
> ![IMG_4967](https://user-images.githubusercontent.com/23347512/115110947-26c3e480-9f7e-11eb-8751-88ac7d87e7e1.PNG)

Are you able to control it?
I have the same Device and for me it only shows one Switch. 
what did you switched on when you claimed the messageId? Did you used HTTP Catcher?

**Comment by iMatux** [comment]
> > > How did you configure it to show in HomeKit?
> > 
> > 
> > Like a supported Meross product, but in config.json model field is set to "MOD-100" ("MOD100" has the same behaviour), maybe is some sort of basic configuration when plugin doesn't recognise the device model.
> > <img alt="Schermata 2021-04-17 alle 13 05 10" width="364" src="https://user-images.githubusercontent.com/23347512/115110935-0f84f700-9f7e-11eb-88c1-c80d8fc9603d.png">
> 
> Are you able to control it?
> I have the same Device and for me it only shows one Switch.
> what did you switched on when you claimed the messageId? Did you used HTTP Catcher?

I can't control it, if I try to send commands with Home app the Homebridge log shows "socket hang up" with the IP address of the diffuser. What did you write in model field?

**Comment by maslcar** [comment]
> > > > How did you configure it to show in HomeKit?
> > > 
> > > 
> > > Like a supported Meross product, but in config.json model field is set to "MOD-100" ("MOD100" has the same behaviour), maybe is some sort of basic configuration when plugin doesn't recognise the device model.
> > > <img alt="Schermata 2021-04-17 alle 13 05 10" width="364" src="https://user-images.githubusercontent.com/23347512/115110935-0f84f700-9f7e-11eb-88c1-c80d8fc9603d.png">
> > 
> > 
> > Are you able to control it?
> > I have the same Device and for me it only shows one Switch.
> > what did you switched on when you claimed the messageId? Did you used HTTP Catcher?
> 
> I can't control it, if I try to send commands with Home app the Homebridge log shows "socket hang up" with the IP address of the diffuser. What did you write in model field?

Ok i get the same error in my logs. 
MOD-100 exactly like you. My PlugIn is 5.0.2

**Comment by bwp91** [comment]
Hi,

Can look into supporting this device in the beta version of the plugin if this is something that would interest you.

Thanks

**Comment by maslcar** [comment]
Hi,

Sure this would be awesome, if you need any information about the device or me for testing just let me know and i will do. 

Best regards.  
Marcel

**Comment by bwp91** [comment]
for my reference:

```json
{
   "digest":{
      "diffuser":{
         "type":"mod100",
         "light":[
            {
               "channel":0,
               "onoff":1,
               "lmTime":1618568005,
               "mode":0,
               "luminance":100,
               "rgb":255
            }
         ],
         "spray":[
            {
               "channel":0,
               "mode":2,
               "lmTime":1618570307
            }
         ]
      }
   }
}
```

**Comment by bwp91** [comment]
@maslcar can you update the plugin to beta version 6.0.1-beta.3 and check that the device now appears as an accessory in homekit?

ideally it should show with two services

* a fan which won't do anything at the moment, i'll use it later to implement the diffuser spray setting
* a light which should work controlling the diffuser light

At the moment I wanna concentrate on the light - could you see if it is working? To test:

* Control the on/off, brightness and colour from **Home app** to check the device actually responds correctly

Also I would like to implement the real time status updates if the device is controlled via meross app (to update the home app status).

Could you use the meross app to change the light ON/OFF, then the brightness, then the colour. When you do each of these, a message should appear in the logs in yellow, something like `real-time diffuser cloud updates not supported` with some data below.

Could you grab me all these logs and post them here?

Thanks
