### ISSUE TITLE
Device Type: mss210n, is currently not supported.

### ISSUE THREAD

**Issue by EpicKris** [bwp91/homebridge-meross#305]
**Is your feature request related to a problem? Please describe.**

Device Type: `mss210n`, is currently not supported.

**Describe the solution you'd like**

Add support for Device Type: `mss210n`.

**Describe alternatives you've considered**

Using `homebridge-meross`.

**Comment by bwp91** [comment]
v6 beta of this plugin is available to try. i'm not sure whether the MSS210N works with the beta, could someone with this device try?

If you update, please read [changelog](https://github.com/bwp91/homebridge-meross/blob/latest/CHANGELOG.md) as there are some config changes, probably easiest to use the homebridge plugin settings screen to redo the config needed
