### ISSUE TITLE
Add Support for MRS100 Rolling Shutter Switch

### ISSUE THREAD

**Issue by rgoggy** [bwp91/homebridge-meross#77]
Can you add MRS Rolling Shutter Switch?

**Comment by rgoggy** [comment]
Can I give any information that someone can implement it?

**Comment by donavanbecker** [comment]
@rgoggy have you used http catcher to get the data that is being set to the plug? if not see [Getting-Credentials](https://github.com/donavanbecker/homebridge-meross/wiki/Getting-Credentials) wiki.

**Comment by facundo59** [comment]
The device it's a roller shutter and has 3 functions, up, down and stop. 

I tried configuring it as a garage door, the most similar accessory, but it does not work unfortunately. 

Let me know what any info you need and I'll post it. 

`{
  "header": {
    "messageId": "1cec8d3b3973b760d4181c6dc49141e5",
    "namespace": "Appliance.System.Online",
    "method": "GETACK",
    "payloadVersion": 1,
    "from": "/appliance/2006098257521090815448e1e91e789e/publish",
    "timestamp": 1603633915,
    "timestampMs": 985,
    "sign": "3bd39b1bfd728cf53ffe1d5ee87744b3"
  },
  "payload": {
    "online": {
      "status": 1
    }
  }
}`

**Comment by rgoggy** [comment]
> @rgoggy have you used http catcher to get the data that is being set to the plug? if not see [Getting-Credentials](https://github.com/donavanbecker/homebridge-meross/wiki/Getting-Credentials) wiki.

Yes
do you need something from Charles Proxy too?

`{
  "payload" : {
    "position" : {
      "channel" : 0,
      "position" : 0
    }
  },
  "header" : {
    "messageId" : "e19e6eb8cd137e5eff3f8ec39e8dd1cb",
    "method" : "SET",
    "from" : "http:\/\/10.0.1.194\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.RollerShutter.Position",
    "sign" : "dcded76d9e710e9e1e3342516b516169",
    "triggerSrc" : "iOS",
    "timestamp" : 1603644635
  }
}`

**Comment by donavanbecker** [comment]
See #151

**Comment by Lui5Jacint0** [comment]
@rgoggy @facundo59 did you get it ti work?

**Comment by rgoggy** [comment]
No I’m waiting for the cloud implementation from @donavanbecker

**Comment by DavTechFr** [comment]
> No I’m waiting for the cloud implementation from @donavanbecker

@rgoggy Why are you waiting for homebridge-meross-cloud?
What is the difference with this plugin (w/o cloud), and why MRS100 cannot be added to it?

Thanks

**Comment by rgoggy** [comment]
> > No I’m waiting for the cloud implementation from @donavanbecker
> 
> @rgoggy Why are you waiting for homebridge-meross-cloud?
> What is the difference with this plugin (w/o cloud), and why MRS100 support cannot be added to this one?
> 
> Thanks

I think new developments are only done in the Cloud Version

**Comment by donavanbecker** [comment]
@rgoggy No both are getting updates.

**Comment by rgoggy** [comment]
@donavanbecker Where can I find the implementation?

**Comment by rgoggy** [comment]
@donavanbecker Any update? Or additional info needed?

**Comment by Lui5Jacint0** [comment]
@donavanbecker any update regarding this feature?

**Comment by facundo59** [comment]
> @donavanbecker any update regarding this feature?

Obviously not. Just gotta be patient, dude is doing this in this free time.

**Comment by stan69b** [comment]
Hello, I've been trying to make the MRS100 work with this plugin, I created a fork : https://github.com/stan69b/homebridge-meross
for now it treats a shutter as a garage door in homekit, i juste duplicated the garageDoor class to a Shutter one and changed the api calls to open or close the shutter. It works, but I have no way of getting the status of the roller shutter so home gets stuck on closing..... or opening.... for a while.

It's a dirty "fix", it does not work well but offers opening and closing shutters. If this fork can help anyone in enhencing this feature, make a proper PR request or juste give info on the api calls needed for an MRS100, i'll be happy :) I'll keep trying out some codes to make it work better, but in this state, it is not PR ready AT ALL !

to install, clone the fork, inside the fork do "npm run build", one built, go up a folder and do npm install homebridge-meross/ (cloned and build dir). make sure to run this command from the homebridge user, i do it from the terminal in the web interface, but make sur pc doesn;t go to sleep, it kills the build otherwise.

**Comment by stan69b** [comment]
Just the payload need changes to work with mrs100, the position object.
`this.Payload = {
      position: {
        channel: this.device.channel || 0,
        position: this.Open ? 100 : 0, // 100 top, 0 bottom, -1 stop.
      },
    };

    // Data Info
    this.Data = {
      payload: this.Payload,
      header: {
        messageId: `${this.device.messageId}`,
        method: 'SET',
        from: `http://${this.device.deviceUrl}/config`,
        namespace: 'Appliance.RollerShutter.Position',
        timestamp: this.device.timestamp,
        sign: `${this.device.sign}`,
        payloadVersion: 1,
        triggerSrc: 'iOSLocal',
      },
    };`

for the status, nothing of interest inside the response sadly, so the code : this.deviceStatus?.payload?.all?.digest?.xxxx won't work the way it works for garage doors. without status, it's hard to make perfect. I tried a timeout from the garageDoor timer, but I can't find the variable which needs to be updated to tell the system that the shutter should be seen as closed or open.

**Comment by stan69b** [comment]
Little info, I spent literally 1h on this, from catching the request and adding them inside the existing code (It is dirty, i give you that). If all of us developer out there give a little hour of our time when available, we can greatly help the developers and their plugins :) I'm mean if you are here, you obviously have a technical background, I'm sure some of you can give a coding hand (even if its not much, if anyone can help me find the api to get shutter status, I can even make a proper PR) ;)

**Comment by facundo59** [comment]
Hey @stan69b, thank you very much for your help. I wish I could help, I already tried hours trying to find a workaround but no success. I do have a technical background, but for my regret it is not related to programming. 

Just a quick though, for the first phases wouldn't a switch be easier to work with than a garage door? 

If I can be any help, let me know!

**Comment by stan69b** [comment]
Hey @facundo59 I took garage door thinking they were similiar but maybe you are right. Do you know any accessory from meross plugin that would allow me 3 buttons ? i would need open/close/stop. 
Idealy i wanted to use the garagedoor timer to trigger "fake states" but did not figure it out yet.

**Comment by stan69b** [comment]
Thanks, I'm going to look through the code and see if I can duplicate a switch and give it more interactions. I can't seem to find in the plugin's code anything that would trigger 3 buttons. With abit of luck, the template I make might be usable for other devices :) (I only have light switch and rollershutter so might not be able to help for new devices if I don't have them)
I'm currently editing on my laptop, pushing, then pulling on my Pi Zero bedroom bridge, build for 5-10 minutes, the testing is not ideal, even worse when compiler sees an error at the end xD I'll try to come up with something today if i can. I will update the fork. If you wan't to test out the code when done, it would really help me into make a proper PR after the functionality is validated :)

**Comment by stan69b** [comment]
Hey again, I've come up with a new approach, still not PR ready as I lack the required knowledge in homebridge plugin developpment but it's a working version :D I do not plan on updating it anymore as it fits my purpose for now. 

Fork is Available at : https://github.com/stan69b/homebridge-meross.git
(also interesting to have a look at the changes with the original as it may give insight on how it works for anyone who would want to take on the rest of the development and perhaps make a PR)

You need to add your device 3 times, one for each action :

`
{
                    "name": "Ouvre Volets Chambre",
                    "model": "MRS100-Open",
                    "firmwareRevision": "2.1.2",
                    "deviceUrl": "192.168.1.18",
                    "messageId": "xxxxx",
                    "timestamp": xxxxx,
                    "sign": "xxxxx"
                },
                {
                    "name": "Ferme Volets Chambre",
                    "model": "MRS100-Close",
                    "firmwareRevision": "2.1.2",
                    "deviceUrl": "192.168.1.18",
                    "messageId": "xxxxx",
                    "timestamp": xxxxx,
                    "sign": "xxxxx"
                },
                {
                    "name": "Stop Volets Chambre",
                    "model": "MRS100-Stop",
                    "firmwareRevision": "2.1.2",
                    "deviceUrl": "192.168.1.18",
                    "messageId": "xxxxx",
                    "timestamp": xxxxx,
                    "sign": "xxxxx"
                },
}
`

the GUI also gives models MRS100-Open/Close/Stop as models

once done, each button will trigger the desired action.
Ideally one should use other homebridge elements with a slider or at lease 3 buttons to interact with.

to install, go to your homebridge web instance, go to terminal and enter : 
`
mkdir downloads && cd downloads && git clone https://github.com/stan69b/homebridge-meross.git && cd homebridge-meross/ && git pull && npm run build && cd .. && npm install homebridge-meross/
`

- create a downloads dir inside homebridge home folder
- go to downloads
- clone fork
- go to cloned fork folder
- pull in case of changes (why not)
- npm run a build of the plugin
- go out of plugin folder
- npm install plugin locally

I had a version of the pugin installed before doing all thins, I do not know if it is required or not.

**Comment by bwp91** [comment]
I can look into supporting this device in the next version of the plugin.

@stan69b is your fork still working for this? For the payload,

```
position: {
  channel: 0,
  position: 100
}
```

For the position property I see earlier you wrote '100 top, 0 bottom, -1 stop.'

Is it possible to send any value between 0 and 100 to specify an exact %-point?

**Comment by bwp91** [comment]
Closing this issue as conversation is in #306

**Comment by stan69b** [comment]
Hi @bwp91 , did not see your question this morning. I switched to HomeAssistant some time ago (because I needed MRS100 support, but turns out it is not supported on HomeAssistant either xD). I havent tested the horrible fork I made in a while. For educational purposes, did the position payload still works and has the fork helped you in any way ? (doesn't matter if it didn't, I would feel a little bit of pride if it did haha)
Have a nice day and thank you again for all your work !

**Comment by bwp91** [comment]
> Hi @bwp91 , did not see your question this morning. I switched to HomeAssistant some time ago (because I needed MRS100 support, but turns out it is not supported on HomeAssistant either xD). I havent tested the horrible fork I made in a while. For educational purposes, did the position payload still works and has the fork helped you in any way ? (doesn't matter if it didn't, I would feel a little bit of pride if it did haha)
> 
> Have a nice day and thank you again for all your work ! 

Yes! I wasn't fully sure of how the states related to open close and stop. so I used the info in your fork re the position namespace to help. I also think if and when meross allow for position based location, it will make it easier to update the code.
So yes your work was used!

**Comment by bwp91** [comment]
@stan69b should switch back to homebridge!

**Comment by stan69b** [comment]
I'm working with sensors (temps, light, proximity, movement) in each room (using a raspberry pi zero in every room). I have soooooooooo much to do manually on Homebridge (unless ....... I missed something ? :D ). HomeAssistant provides an interface based automation setup system and works with mqtt for sensors data updates, it seemed easer for now.

point is to have a fully automated house, closing shades if too much sun and temp too hight, turn off light is room is empty, make music follow me in every rooms.... I'm secretly hoping I can find a way to manage shutters the jedi way with the force xD 

I do love the "from scratch" way.... but damn it takes too much time haha project is currently idle sadly. Hoping to get back to it soon.
